export const UNIVERSITIES_LIST = [
  "Air Force Institute of Technology (AFIT), Kaduna",
  "Abia State University, Uturu",
  "Achievers University, Owo",
  "Adamawa State University, Mubi",
  "Adekunle Ajasin University, Akungba",
  "Adeleke University, Ede",
  "Afe Babalola University, Ado-Ekiti",
  "African University of Science and Technology, Abuja",
  "Ahmadu Bello University, Zaria",
  "Ajayi Crowther University, Oyo",
  "Akwa Ibom State University, Ikot Akpaden",
  "Al-Hikmah University, Ilorin",
  "Al-Qalam University, Katsina",
  "Alex Ekwueme Federal University, Ndufu-Alike",
  "Ambrose Alli University, Ekpoma",
  "American University of Nigeria, Yola",
  "Anchor University, Lagos",
  "Arthur Jarvis University, Akpabuyo",
  "Augustine University, Ilara",
  "Babcock University, Ilishan-Remo",
  "Bauchi State University, Gadau",
  "Bayero University, Kano",
  "Baze University, Abuja",
  "Bells University of Technology, Ota",
  "Benson Idahosa University, Benin City",
  "Benue State University, Makurdi",
  "Bingham University, Karu",
  "Bowen University, Iwo",
  "Caleb University, Lagos",
  "Caritas University, Enugu",
  "Chrisland University, Abeokuta",
  "Chukwuemeka Odumegwu Ojukwu University, Uli",
  "Coal City University, Enugu",
  "Covenant University, Ota",
  "Crawford University, Igbesa",
  "Crescent University, Abeokuta",
  "Cross River State University of Technology, Calabar",
  "Delta State University, Abraka",
  "Dominican University, Ibadan",
  "Ebonyi State University, Abakaliki",
  "Edo State University, Uzairue",
  "Edwin Clark University, Kiagbodo",
  "Ekiti State University, Ado-Ekiti",
  "Elizade University, Ilara-Mokin",
  "Enugu State University of Science and Technology",
  "Federal University Birnin Kebbi",
  "Federal University Dutse",
  "Federal University Dutsin-Ma",
  "Federal University Gashua",
  "Federal University Gusau",
  "Federal University Kashere",
  "Federal University Lafia",
  "Federal University Lokoja",
  "Federal University of Agriculture, Abeokuta",
  "Federal University of Agriculture, Makurdi",
  "Federal University of Petroleum Resources, Effurun",
  "Federal University of Technology, Akure",
  "Federal University of Technology, Minna",
  "Federal University of Technology, Owerri",
  "Federal University Otuoke",
  "Federal University Oye-Ekiti",
  "Federal University Wukari",
  "Fountain University, Oshogbo",
  "Godfrey Okoye University, Enugu",
  "Gombe State University, Gombe",
  "Gregory University, Uturu",
  "Hallmark University, Ijebu-Itele",
  "Ibrahim Badamasi Babangida University, Lapai",
  "Igbinedion University, Okada",
  "Imo State University, Owerri",
  "Joseph Ayo Babalola University, Ikeji-Arakeji",
  "Kaduna State University, Kaduna",
  "Kano University of Science and Technology, Wudil",
  "Kebbi State University of Science and Technology, Aliero",
  "Kings University, Ode-Omu",
  "Kogi State University, Anyigba",
  "Kwara State University, Malete",
  "Ladoke Akintola University of Technology, Ogbomoso",
  "Lagos State University, Lagos",
  "Landmark University, Omu-Aran",
  "Lead City University, Ibadan",
  "Madonna University, Okija",
  "Mcpherson University, Seriki Sotayo",
  "Michael Okpara University of Agriculture, Umudike",
  "Mountain Top University, Makogi",
  "Nasarawa State University, Keffi",
  "Niger Delta University, Wilberforce Island",
  "Nigerian Army University, Biu",
  "Nigerian Defence Academy, Kaduna",
  "Nigerian Maritime University, Okerenkoko",
  "Nigerian Police Academy, Wudil",
  "Nnamdi Azikiwe University, Awka",
  "Northwest University, Kano",
  "Novena University, Ogume",
  "Obafemi Awolowo University, Ile-Ife",
  "Obong University, Obong Ntak",
  "Olabisi Onabanjo University, Ago-Iwoye",
  "Osun State University, Osogbo",
  "Pan-Atlantic University, Lagos",
  "Plateau State University, Bokkos",
  "Redeemer's University, Ede",
  "Renaissance University, Enugu",
  "Rivers State University, Port Harcourt",
  "Salem University, Lokoja",
  "Skyline University, Kano",
  "Sokoto State University, Sokoto",
  "Southwestern University, Oku Owa",
  "Summit University, Offa",
  "Tai Solarin University of Education, Ijebu-Ode",
  "Taraba State University, Jalingo",
  "Thomas Adewumi University, Oko",
  "Umar Musa Yar'adua University, Katsina",
  "University of Abuja",
  "University of Benin, Benin City",
  "University of Calabar",
  "University of Delta, Agbor",
  "University of Ibadan",
  "University of Ilorin",
  "University of Jos",
  "University of Lagos",
  "University of Maiduguri",
  "University of Medical Sciences, Ondo",
  "University of Nigeria, Nsukka",
  "University of Port Harcourt",
  "University of Uyo",
  "Usmanu Danfodiyo University, Sokoto",
  "Veritas University, Abuja",
  "Wesley University, Ondo",
  "Western Delta University, Oghara",
  "Yobe State University, Damaturu",
  "Zamfara State University, Talata-Mafara",
  "Abia State Polytechnic, Aba",
  "Abubakar Tatari Ali Polytechnic, Bauchi",
  "Auchi Polytechnic, Auchi",
  "Benue State Polytechnic, Ugbokolo",
  "Federal Polytechnic Ado-Ekiti",
  "Federal Polytechnic Bauchi",
  "Federal Polytechnic Bida",
  "Federal Polytechnic Damaturu",
  "Federal Polytechnic Ede",
  "Federal Polytechnic Idah",
  "Federal Polytechnic Ilaro",
  "Federal Polytechnic Mubi",
  "Federal Polytechnic Nasarawa",
  "Federal Polytechnic Nekede",
  "Federal Polytechnic Offa",
  "Federal Polytechnic Oko",
  "Hassan Usman Katsina Polytechnic",
  "Hussaini Adamu Federal Polytechnic, Kazaure",
  "Imo State Polytechnic, Umuagwo",
  "Kaduna Polytechnic, Kaduna",
  "Kano State Polytechnic, Kano",
  "Kwara State Polytechnic, Ilorin",
  "Lagos State Polytechnic, Ikorodu",
  "Moshood Abiola Polytechnic, Abeokuta",
  "Nuhu Bamalli Polytechnic, Zaria",
  "Plateau State Polytechnic, Barkin Ladi",
  "Port Harcourt Polytechnic",
  "Ramat Polytechnic, Maiduguri",
  "Rufus Giwa Polytechnic, Owo",
  "The Polytechnic, Ibadan",
  "Waziri Umaru Federal Polytechnic, Birnin Kebbi",
  "Yaba College of Technology, Lagos",
];

export const PROGRAMMES_LIST = [
  "Accounting","Actuarial Science","Adult Education","Aerospace Engineering",
  "Agricultural Economics","Agricultural Education","Agricultural Engineering",
  "Agricultural Extension","Agriculture","Agronomy","Animal Production",
  "Applied Biology","Applied Chemistry","Applied Geophysics","Applied Mathematics","Applied Physics",
  "Arabic and Islamic Studies","Architecture","Banking and Finance","Biochemistry","Biology",
  "Biomedical Engineering","Botany","Building","Business Administration","Business Education",
  "Cell Biology and Genetics","Chemical Engineering","Chemistry","Christian Religious Studies",
  "Civil Engineering","Communication Engineering","Computer Engineering","Computer Science",
  "Cooperative Economics and Management","Criminology and Security Studies","Crop Science",
  "Cyber Security","Data Science","Economics","Electrical Engineering",
  "Electrical/Electronic Engineering","Electronic and Computer Engineering","English Language",
  "English and Literature","Entrepreneurship","Environmental Biology","Environmental Management",
  "Environmental Science","Estate Management","Finance","Fine Arts","Fisheries and Aquaculture",
  "Food Science and Technology","Forestry and Wildlife Management","Genetics and Biotechnology",
  "Geography","Geological Engineering","Geology","Geophysics","Guidance and Counselling",
  "History","History and International Studies","Home Economics Education","Human Anatomy",
  "Human Physiology","Human Resource Management","Industrial Chemistry","Industrial Engineering",
  "Industrial Mathematics","Industrial Physics","Information Technology","Insurance",
  "International Relations","Islamic Studies","Journalism","Law","Library and Information Science",
  "Linguistics","Literature in English","Management","Marketing","Mass Communication",
  "Mathematics","Mathematics Education","Mechanical Engineering","Mechatronics Engineering",
  "Medical Biochemistry","Medical Laboratory Science","Medicine and Surgery",
  "Metallurgical and Materials Engineering","Microbiology","Mining Engineering","Music",
  "Nursing Science","Nutrition and Dietetics","Optometry","Pharmacy","Philosophy",
  "Physical and Health Education","Physics","Physics Education","Physics with Electronics",
  "Physiotherapy","Plant Science","Political Science","Psychology","Public Administration",
  "Pure and Applied Chemistry","Pure and Applied Mathematics","Quantity Surveying","Radiography",
  "Religious Studies","Software Engineering","Soil Science","Statistics","Structural Engineering",
  "Surveying and Geoinformatics","Systems Engineering","Taxation","Telecommunications Engineering",
  "Theatre Arts","Town Planning","Urban and Regional Planning","Veterinary Medicine",
  "Visual Arts","Water Resources Engineering","Zoology",
  "Accountancy","Agricultural Technology","Architectural Technology","Art and Design",
  "Automobile Engineering Technology","Building Technology","Business Administration and Management",
  "Civil Engineering Technology","Computer Science Technology","Electrical/Electronic Engineering Technology",
  "Food Technology","Hotel and Catering Management","Mechanical Engineering Technology",
  "Medical Laboratory Technology","Office Technology and Management",
  "Science Laboratory Technology","Tourism and Travel Management",
];

export const ROTATING_TIPS = [
  "Break complex tasks down into simple components to master concepts efficiently.",
  "Review incorrect answers immediately after drills to reinforce permanent memory.",
  "Consistency beats cramming. Running 10-question drills daily keeps your mind sharp.",
  "Use Practice Mode to target your weak spots before transitioning to timed test environments.",
  "Success is the sum of small efforts repeated day in and day out.",
  "The secret of getting ahead is getting started.",
  "Study hard in silence; let success make the noise.",
  "Every expert was once a beginner. Keep drilling.",
];

export const SEEDS = [
  { code: "AFIT-GST108", title: "Use Of Library, Study Skills And ICT" },
  { code: "PHY104",      title: "General Physics IV (Vibration, Waves And Optics)" },
  { code: "STA112",      title: "Probability I" },
  { code: "TEE102",      title: "Introduction To Telecommunications Engineering" },
  { code: "GET102",      title: "Engineering Graphics And Solid Modelling I" },
  { code: "PHY108",      title: "General Practical Physics II" },
  { code: "PHY102",      title: "General Physics II" },
  { code: "MTH102",      title: "Elementary Mathematics II" },
  { code: "CHM108",      title: "General Chemistry Practical II" },
  { code: "CHM102",      title: "General Chemistry II" },
  { code: "GST112",      title: "Nigerian Peoples And Culture" },
];
